# -*- coding: utf-8 -*-
"""Lab-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UqOdi7pxqnd_O-tYwNf8srtskSoo_z__
"""

import requests

req = requests.get("https://en.wikipedia.org/wiki/Harvard_University")

req
type(req)

dir(req)

page = req.text
page

"""Beautiful Soup"""

from bs4 import BeautifulSoup
soup = BeautifulSoup(page, 'html.parser')
soup

type(page)

type(soup)

print(soup.prettify())

soup.title

"title" in dir(soup)

soup.p

len(soup.find_all("p"))

soup.table["class"]

"""List Comprehensions"""

[t["class"] for t in soup.find_all("table") if t.get("class")]

my_list = []
for t in soup.find_all("table"):
    if t.get("class"):
        my_list.append(t["class"])
my_list

table_html = str(soup.find_all("table", "wikitable")[2])

from IPython.core.display import HTML

HTML(table_html)

rows = [row for row in soup.find_all("table", "wikitable")[2].find_all("tr")]
rows

"""Lamda Functions and Functions"""

rem_nl = lambda s: s.replace("\n", " ")

#functions in python
def product(a,b):
    return a*b;
product(10,5)

def printName():
    return "hello"
print(printName())

def power(x, y):
    return x**y

power(2, 3)

def defaultValues(x,y=1):
    return x*y
print(defaultValues(2))
print(defaultValues(2,3))

def multipleDValues(x,y="Sum is",z=1):
    print(y, x+z)
multipleDValues(2)
multipleDValues(2, "Sum of two numbers", 4)

def print_greeting():
    print("Hello!")
    
print_greeting()

def printAll(name, *listV):
    print(name, "has the following values:")
    for i in listV:
        print(i)
    print
        
printAll("List", 1, 2, 3)
printAll("List", 1)
printAll("List")

def get_multiple(x, y=1):
    return x*y

print("With x and y: ", get_multiple(10, 2))
print("With x only: ", get_multiple(10))

"""Split the data"""

columns = [rem_nl(col.get_text()) for col in rows[0].find_all("th") if col.get_text()]
columns

indexes = [row.find("th").get_text() for row in rows[1:]]
indexes

HTML(table_html)

to_num = lambda s: s[-1] == "%" and int(s[:-1]) or None

values = [to_num(rem_nl(value.get_text())) for row in rows[1:] for value in row.find_all("td")]
values

stacked_values = zip(*[values[i::3] for i in range(len(columns))])
list(stacked_values)

HTML(table_html)

def print_args(arg1, arg2, arg3):
    print(arg1, arg2, arg3)

# Print three numbers.
print_args(1, 2, 3)

# Print three lists.
print_args([1, 10], [2, 20], [3, 30])

parameters = [100, 200, 300]

p1 = parameters[0]
p2 = parameters[1]
p3 = parameters[2]

print_args(p1, p2, p3)

import pandas as pd

stacked_values = zip(*[values[i::3] for i in range(len(columns))])
pText = pd.DataFrame(stacked_values, columns=columns, index=indexes)
pText

columns = [rem_nl(col.get_text()) for col in rows[0].find_all("th") if col.get_text()]
stacked_values = zip(*[values[i::3] for i in range(len(columns))])
data_dicts = [{col: val for col, val in zip(columns, col_values)} for col_values in stacked_values]
data_dicts

pd.DataFrame(data_dicts, index=indexes)

stacked_colValues = [values[i::3] for i in range(len(columns))]
stacked_colValues

data_lists = {col: val for col, val in zip(columns, stacked_colValues)}
data_lists

pd.DataFrame(data_lists, index=indexes)

pText.dtypes

pText.dropna()

pText.dropna(axis=1)

pTextOpti = pText.fillna(0).astype(int)
pTextOpti

pTextOpti.dtypes

pTextOpti.describe()

import numpy as nump

pTextOpti.values

type(pTextOpti.values)

nump.mean(pTextOpti.Undergrad)

nump.std(pTextOpti)

pTextOpti["Undergrad"]

pTextOpti.Undergrad

pTextOpti.loc["Asian/Pacific Islander\n"]

pTextOpti.iloc[0]

pTextOpti.ix["Asian/Pacific Islander\n"]

pTextOpti.ix[0]

pTextOpti.loc["White/non-Hispanic\n", "Graduate"]

pTextOpti.ix[3, "Graduate"]

pTextOpti.loc[3, 1]

sequenceTable = pTextOpti.stack().reset_index()
sequenceTable.columns = ["race", "source", "percentage"]
sequenceTable

groupedData = sequenceTable.groupby("race")
groupedData.groups

type(groupedData)

meanTable = groupedData.mean()
meanTable

type(meanTable)

for name, group in sequenceTable.groupby("source", sort=True):
    print(name)
    print(group)

# %matplotlib inline

meanTable.plot(kind="bar");



